.SUFFIXES:

MAKEFLAGS += --no-print-directory

ifeq ($(strip $(DEVKITPRO)),)
$(error "Set DEVKITPRO in your environment. (export DEVKITPRO=/opt/devkitpro)")
endif

TOPDIR ?= $(CURDIR)

include $(DEVKITPRO)/libnx/switch_rules

TARGET      :=  ZeldaRotH_nx
APP_TITLE   := Zelda - Return of the Hylian
APP_AUTHOR  := Vincent Jouillat (Switch port by Worthis)
APP_VERSION := 7.10.0.2
APP_ICON    := $(TOPDIR)/icon.jpg
export APP_TITLE APP_AUTHOR APP_VERSION APP_ICON

BUILD       :=  build
ifneq ($(wildcard src/.),)
    SOURCES := $(shell find src -type d)
    export SOURCES
endif
INCLUDES := include

ARCH    :=  -march=armv8-a+crc+crypto -mtune=cortex-a57 -mtp=soft -fPIE

CFLAGS   :=  -g -Wall -O2 -ffunction-sections $(ARCH) $(DEFINES)
CFLAGS   +=  $(INCLUDE) -D__SWITCH__
CXXFLAGS := $(CFLAGS) -std=gnu++14
ASFLAGS  :=  -g $(ARCH)
LDFLAGS  =   -specs=$(DEVKITPRO)/libnx/switch.specs -g $(ARCH) -Wl,-Map,$(notdir $*.map)

LIBS    :=  -lSDL2_mixer -lmodplug -lmpg123 -lvorbisfile -lopusfile -lopus -lvorbis -logg \
            -lSDL2_image -lpng -ljpeg -lwebp \
            -lSDL2 -lEGL -lglapi -ldrm_nouveau -lnx -lm -lz

LIBDIRS :=  $(PORTLIBS) $(LIBNX)

ifneq ($(BUILD),$(notdir $(CURDIR)))
export OUTPUT   :=  $(CURDIR)/$(TARGET)
export TOPDIR   :=  $(CURDIR)
export VPATH    :=  $(foreach dir,$(SOURCES),$(CURDIR)/$(dir))
export DEPSDIR  :=  $(CURDIR)/$(BUILD)

CFILES   :=  $(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.c)))
CPPFILES :=  $(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.cpp)))
SFILES   :=  $(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.s)))

ifeq ($(strip $(CPPFILES)),)
    export LD   :=  $(CC)
else
    export LD   :=  $(CXX)
endif

export OFILES_SRC   :=  $(CPPFILES:.cpp=.o) $(CFILES:.c=.o) $(SFILES:.s=.o)
export OFILES       :=  $(OFILES_SRC)

export INCLUDE  :=  $(foreach dir,$(INCLUDES),-I$(CURDIR)/$(dir)) \
                    $(foreach dir,$(LIBDIRS),-I$(dir)/include) \
                    $(foreach dir,$(SOURCES),-I$(CURDIR)/$(dir))

export LIBPATHS :=  $(foreach dir,$(LIBDIRS),-L$(dir)/lib)

.PHONY: $(BUILD) clean all

all: $(BUILD)

$(BUILD):
	@[ -d $@ ] || mkdir -p $@
	@$(MAKE) --no-print-directory -C $(BUILD) -f $(CURDIR)/Makefile.switch

clean:
	@echo "clean ..."
	@rm -fr $(BUILD) $(TARGET).elf $(TARGET).nro $(TARGET).nacp

else

NROFLAGS := --icon=$(APP_ICON) --nacp=$(OUTPUT).nacp

all : $(OUTPUT).nro
$(OUTPUT).nro : $(OUTPUT).elf $(OUTPUT).nacp
$(OUTPUT).elf : $(OFILES)

-include $(DEPSDIR)/*.d

endif